### ISSUE TITLE
Vcluster not work in openshift when distro is eks or k8s

### ISSUE THREAD

**Issue by flacatus** [loft-sh/vcluster#1030]
### What happened?

Jobs to create virtual cluster for eks and k8s are not working due security context issues:

Error creating: pods "vcluster-job-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "pipelines-scc": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 10001: must be in the ranges: [1001070000, 1001079999], provider "restricted":

### What did you expect to happen?

Deploy vcluster eks distro

### How can we reproduce it (as minimally and precisely as possible)?

1. Have openshift cluster
2. execute: vcluster create vcluster -n fla-vcluster-2 --distro=k8s --expose --create-namespace

### Host cluster Kubernetes version

Openshift 4.12

### Host cluster Kubernetes distribution

1.25

### vlcuster version

latest

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by rohantmp** [comment]
Hi, thanks for the issue. We do need some extra configuration for openshift as documented here: https://www.vcluster.com/docs/operator/restricted-hosts

You can configure runAsUser to be in the valid range, and run as rootless. There is also an `openshift` flag

Since the error is related to the setting mentioned in this doc, I am closing this issue. If this still does not work with the mentioned settings, feel free to reopen the issue :)
