### ISSUE TITLE
Timeout issues with slow kube api in host cluster

### ISSUE THREAD

**Issue by cinimins** [loft-sh/vcluster#1117]
### What happened?

I have a vCluster 0.14.0 k0s set up. Aside from the vcluster, our kubernetes cluster seems to have network issues at the moment. The kube API is really slow with responding to any kind of requests. The admins are working on it, and when communicating with the kube api of the host cluster directly, everything works, although it's slow.

When I try to do a helm upgrade within a vCluster though, I run into a timeout, e.g.:

```
Error: UPGRADE FAILED: Get "https://vcluster.example/api/v1/namespaces/my-namespace/services/my-service": dial tcp 1.2.3.4:443: i/o timeout
```

As a next step, I increased the timeout (which is by default 5m0) with `helm upgrade --timeout 1h`, but I still run into the same timeouts after very few minutes (the parameter does not have an impact on this issue). Is it possible that the timeout happens between the vClusters kube API and the host kube API and the timeout threshold is not forwarded?

### What did you expect to happen?

* 

### How can we reproduce it (as minimally and precisely as possible)?

* 

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```

</details>

**Comment by ishankhare07** [comment]
Hey @cinimins , thanks for creating this issue but it looks like this is mostly got to do with the connectivity issues with your host cluster. I can confirm from the following snippets below

https://github.com/loft-sh/vcluster/blob/main/cmd/vcluster/cmd/start.go#L134

https://github.com/loft-sh/vcluster/blob/main/cmd/vcluster/cmd/start.go#L260

That we set the timeouts for host and cirtual API server clients to be 0 which effectively means [no timeout](https://pkg.go.dev/k8s.io/client-go@v0.27.2/rest#Config.Timeout)

Also looking at the helm cli error you reported above, seems like the upgrade failed because helm could never reachout to the vcluster itself for the the upgrade to start.
