### ISSUE TITLE
vcluster isolated mode fails during creation

### ISSUE THREAD

**Issue by muedan** [loft-sh/vcluster#1134]
### What happened?

I've tried to create a vcluster on Docker Desktop enabled Kubernetes with isolation mode but it failed to deploy, here the output of the vcluster command:

```
vcluster create test --isolate 
info   Creating namespace vcluster-test
info   failed to find IPv6 service CIDR: couldn't find host cluster Service CIDR ("Service "test-service-ndsfd" is invalid: spec.clusterIPs[0]: Invalid value: []string{"2001:DB8::1"}: IPv6 is not configured on this cluster")
info   Detected local kubernetes cluster docker-desktop. Will deploy vcluster with a NodePort & sync real nodes
info   Chart not embedded: "open charts/vcluster-0.15.2.tgz: file does not exist", pulling from helm repository.
info   Create vcluster test...
info   execute command: helm upgrade test https://charts.loft.sh/charts/vcluster-0.15.2.tgz --kubeconfig /var/folders/hg/xv0q4jfs3mb82d6wrcwycbpr0000gn/T/2269843698 --namespace vcluster-test --install --repository-config='' --values /var/folders/hg/xv0q4jfs3mb82d6wrcwycbpr0000gn/T/247410622
fatal  error executing helm upgrade test https://charts.loft.sh/charts/vcluster-0.15.2.tgz --kubeconfig /var/folders/hg/xv0q4jfs3mb82d6wrcwycbpr0000gn/T/2269843698 --namespace vcluster-test --install --repository-config='' --values /var/folders/hg/xv0q4jfs3mb82d6wrcwycbpr0000gn/T/247410622: Release "test" does not exist. Installing it now.
Error: 1 error occurred:
	* services "test" is forbidden: exceeded quota: test-quota, requested: services.nodeports=2, used: services.nodeports=0, limited: services.nodeports=0
```

### What did you expect to happen?

The test cluster should be created

### How can we reproduce it (as minimally and precisely as possible)?

```
vcluster create test --isolate 
```

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version --short
# Client Version: v1.27.4
# Kustomize Version: v5.0.1
# Server Version: v1.27.2
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# NAME             STATUS   ROLES           AGE   VERSION
# docker-desktop   Ready    control-plane   5d    v1.27.2
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# vcluster version 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# default
```

</details>

### OS and Arch

<details>

```
OS: macOS Monterey 12.6.8
Arch: x64
```

</details>

**Comment by ThomasK33** [comment]
Hello @muedan 👋,

Thank you for the detailed report. From what I can see, the observed behavior is _technically_ correct. When you run vcluster in isolation mode, no NodePort services are allowed. You can see this reflected in the last line of the output.

By default, the vcluster CLI attempts to create a NodePort service when it detects a local Kubernetes distribution. In your case, it detected Docker Desktop, and, by default, it tried to make a service with two NodePorts. The process fails since the limit is zero in isolation mode.

There is a flag that can control this behavior. You can try to use the `--expose-local=false` flag. So, the full command that should work with the Docker Desktop Kubernetes cluster would be:

```bash
vcluster create test --isolate --expose-local=false
```

This command will create the vcluster without attempting to expose it locally via a NodePort service.

Please try the above command and let us know if you still encounter any issues.
