### ISSUE TITLE
Allow to enforce AlwaysPullImages in Admission Controller

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#1157]
### Is your feature request related to a problem?

Let's say you had a pod that uses image as `myapp:master` and `imagePullPolicy` as `IfNotPresent` in one vcluster. Then:

1. `myapp:master` gets updated with another revision
2. You create another vcluster in the same host cluster which has a single node
3. You try to deploy the same pod.

The image cached from the first vcluster will cause the second vcluster not to pull the image again.

I understand why that happens, but I believe this severely breaks isolation between the vclusters. At least for my use case for example, I can no longer rely on tags like `pr-<pr number>` to run tests in CI for PRs, I have to tag with something like `<git sha>` instead.

I only realized this now, and otherwise this could have caused unpredicted consequences.

### Which solution do you suggest?

It would be amazing if vcluster could isolate this as well. Maybe:

1. vcluster control plane to save a dictionary of "known images", which would be always empty when started
2. When deploying a pod, vcluster first checks if `imagePullPolicy` is set as `IfNotPresent` and then checks if the image is within the list of "known images" for that vcluster. If it is not, vcluster automatically patches the pod to ensure `imagePullPolicy` is `Always`.

Maybe there is a cleaner way to implement?

### Which alternative solutions exist?

Ensure tags are always unique. Or ensure imagePullPolicy is always Always. This is a complicated measure.

### Additional context

Ensure tags are always unique. Or ensure imagePullPolicy is always Always. This is a complicated measure.

**Comment by ThomasK33** [comment]
Hello @felipecrs,

Thank you for raising this issue and providing a detailed description of your use case and challenges.

First, your observation about how vclusters interact with image caches in the host cluster is correct. When one namespace in a host cluster pulls an image, it makes sense for another namespace to use the cached version of that same image and tag rather than pulling it again. This behavior is by design, given by Kubernetes itself, and is intended for efficiency.

Regarding your suggestion to have vcluster maintain a dictionary of "known images" and adjust the imagePullPolicy based on that, it's a thoughtful idea. However, there are some considerations:

1. Complexity: Implementing this would introduce complexity to the vcluster core. While potentially valuable, this might be better approached using other mechanisms, such as a custom mutating admission controller or a custom syncer.
2. Community Edition vs. Commercial Product: Given vcluster's open-source nature, this strict isolation may not fit as a feature for the community edition. However, we recognize its value in more professional or commercial deployments, so we would like to keep it in mind for future announcements about a commercial product. We're considering many features there that can provide advanced isolation and optimization.

As an immediate workaround and based on your provided context, you're correct in noting that making tags unique or adjusting imagePullPolicy can help. Yet, I understand that these solutions can be cumbersome. We genuinely appreciate your feedback and will certainly consider it as we refine and expand vcluster.

**Comment by felipecrs** [comment]
I'm pretty sure you used ChatGPT to answer me, lol.

> First, your observation about how vclusters interact with image caches in the host cluster is correct. When one namespace in a host cluster pulls an image, it makes sense for another namespace to use the cached version of that same image and tag rather than pulling it again. This behavior is by design, given by Kubernetes itself, and is intended for efficiency.

I don't agree with this reasoning. It makes total sense for different namespaces within a cluster, but makes no sense for different vclusters.

If one vcluster can interfere with the function of another vcluster, then surely we have a flaw in the isolation which is what I'm trying to clarify with this issue.

Nevertheless, I understand if you decide to make this a feature of vcluster pro instead: higher pay = higher isolation.

**Comment by FabianKramm** [comment]
@felipecrs isn't using something like `:latest` and `:master` a big anti pattern even for PRs etc, this sounds like a big race condition to me if you are betting on the latest master tag to be always the PR, like what happens if there are 2 PRs at the same time? Wouldn't it be a lot better to use the git sha in general? Also what prevents you form using `imagePullPolicy: Always`, wouldn't this be the better solution as you can control what images should get repulled and what you want to share across clusters?

**Comment by FabianKramm** [comment]
@felipecrs what about a vcluster flag that just sets `imagePullPolicy: Always` for all synced pods? This would solve the problem with the downside of extra (sometimes unnecessary) network traffic

**Comment by felipecrs** [comment]
That would be awesome! Great idea!

**Comment by felipecrs** [comment]
BTW: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages

**Comment by felipecrs** [comment]
I renamed the issue for better clarity on what should be done.

**Comment by felipecrs** [comment]
It looks like I can already set this with:

```yaml
vcluster:
  extraArga:
    - --kube-apiserver-arg=enable-admission-plugins=AlwaysPullImages
```

I will test it now.

**Comment by felipecrs** [comment]
Works like a charm!
