### ISSUE TITLE
Question - how can I see how the Kubernetes components are configured by default?

### ISSUE THREAD

**Issue by jiglesia3** [loft-sh/vcluster#1185]
Hello, I have a k3s vcluster deployed with the latest version (0.15.7), and I'd like to look further into the Kubernetes components that are included as part of the deployment, specifically the kube-controller-manager and kube-api-server. I'm able to exec into a running vcluster container (in the vcluster-0) pod, but I'm not able to find much. 

Thanks.

**Comment by neogopher** [comment]
Hi @jiglesia3 :wave,
Thanks for creating the issue. 

K3s by design is packaged as a single binary including all things needed to run kubernetes including the control plane components like kube-controller-manager, kube-api-server, etc. Hence, you will not be able to see them seperately as in the case of K8s distro. You can refer to the [K3s Docs](https://docs.k3s.io/) for more information of how K3s works, its architecture and features. 

Is there anything else we could help you with. :slightly_smiling_face:

**Comment by jiglesia3** [comment]
> 

Thanks, I've seen those docs. I guess I'm just trying to see more into the running k3s server specifically in this context of a vcluster deployment. I'm on the vcluster container and see the process running below, but I'm unsure on how to access any logs for it. 

```Shell
/ # ps -a
PID   USER     COMMAND
    1 0        /bin/sh -c /bin/k3s server --write-kubeconfig=/data/k3s-config/kube-config.yaml --data-dir=/data --disable=traefik,servicelb,metrics-server,local-storage,coredns --disable-network-policy --disable-agent --disable-cloud-controller --flannel-backend=none
```

**Comment by neogopher** [comment]
Well, you can run the below command from the host cluster to access the logs for the vcluster container (K3s API Server).
`kubectl logs <vcluster-name>-0 -n <vcluster-namespace> -c vcluster`

**Comment by jiglesia3** [comment]
Ah, thanks! I was hellbent on looking directly in the container itself and forgot to check logs that way. Appreciate the quick responses.
