### ISSUE TITLE
Remove advertisement for cluster-api

### ISSUE THREAD

**Issue by everflux** [loft-sh/vcluster#1345]
### What happened?

I decided to evaluate vcluster based on the Cluster-API support mentioned on the vcluster github main page. Now I realized that capi is no longer support.

### What did you expect to happen?

Advertised features to be available and kept roughly up to date.

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/loft-sh/cluster-api-provider-vcluster/issues/39

### Anything else we need to know?

There are quite some users of the capi as can be seen on slack as well. It would be great if this could be kept alive or a suitable alternative using a CRD could be provided.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@everflux thanks for creating this issue! Where do you read its not supported anymore? Yes we are lacking a couple of versions behind, but we are working on that

**Comment by kingdonb** [comment]
The cluster-api provider has not been updated since 2022, I tried upgrading it today because I've found that although I figured out how to pin the k3s version to a recent one, the vcluster chart is still at 0.11.1, it was set as the default in that CAPI provider release 0.1.3 and hasn't been changed since then.

I wouldn't have noticed this, but I've been fighting an issue with coredns that I don't see reported anywhere, and I finally was able to trace it back to this older version of the chart being mismatched with the `coredns/coredns:latest` that it deploys!

(You need to have some cap_sys bind network port permission in order to use port 53, the coredns on each of my vclusters started to fail on cluster upgrade as a result of this... I guess the answer would be to upgrade the vcluster via CAPI, but it seems to not be possible to do it that way...)

I tried upgrading my VCluster resource to one like this:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  ...
spec:
  controlPlaneEndpoint:
    host: moo-cluster.turkey.local
    port: 443
  helmRelease:
    chart:
      name: vcluster
      version: 0.17.1
    values: |-
      vcluster:
        image: rancher/k3s:v1.27.8-k3s1
```

This failed. The error:

```
    Reason:                HelmDeployFailed
    Severity:              Error
    Status:                False
    Type:                  HelmChartDeployed
    Last Transition Time:  2023-05-15T01:19:25Z
    Status:                True
    Type:                  KubeconfigReady
  Initialized:             true
  Message:                 error installing / upgrading vcluster: error executing helm upgrade: Error: UPGRADE FAILED: parse error at (vcluster/templates/_helpers.tpl:28): unclosed action
```

I was able to do the upgrade manually, with `helm upgrade`, so it doesn't seem to be an error in the chart! It's good to hear it's still supported, (do you need any help to corral all of these issues?)

**Comment by guettli** [comment]
Fabian:

> Where do you read its not supported anymore? 

I read it here: https://kubernetes.slack.com/archives/C03NYNV9E10/p1698404596961829?thread_ts=1698401185.803449&cid=C03NYNV9E10

**Comment by lknite** [comment]
In my homelab [daytwo](https://github.com/lknite/daytwo) is used to add vclusters to argocd automatically (via capi) as well as to manage pinniped automatically.  The result is I never need to pull an admin kubeconfig.

It's all just so convenient that so far I'm willing to remain at whatever version is supported by the vcluster provider.  Looking forward to updates whenever they become available.

**Comment by kingdonb** [comment]
The coredns failure is a small price to pay, but it would be nice to see it patched 🚀

**Comment by FabianKramm** [comment]
@everflux @kingdonb @lknite @guettli we are currently in the works of starting to actively maintain this again. We will update dependencies, add tests and then update the supported vcluster version.

**Comment by kingdonb** [comment]
That's great news! I was meaning to try forking and publish a release on my own, but I'm afraid that the hooks in cluster-api upstream will make it exceedingly difficult for anyone else to provide the next version from an outside fork.

If you need testers or want to build community in somehow else, I'm more than happy to participate.

**Comment by deniseschannon** [comment]
@kingdonb We released a new CAPI release [v0.2.0-alpha.1](https://github.com/loft-sh/cluster-api-provider-vcluster/releases/tag/v0.2.0-alpha.1) a couple of weeks ago and are looking for feedback. If you test it and face any issues, let me know. 

For the rest of those on this ticket, I"m going to close this as we are aiming to actively maintain it.

**Comment by guettli** [comment]
> I"m going to close this as we are aiming to actively maintain it.

Thank you for the good news!

**Comment by deniseschannon** [comment]
@guettli We have a current v0.2.0-alpha.1 available that we are looking for community feedback. If you have a chance to try it out, that'd be great!
