### ISSUE TITLE
Vcluster in AKS

### ISSUE THREAD

**Issue by vivuu1989** [loft-sh/vcluster#1399]
### Is your feature request related to a problem?

We are running our AKS clusters v1.27 in our 3 non prod subscriptions 2 prod subscriptions and configured in different spokes with Azure CNI enabled(virtual network). Also using istio as servicemesh on each the clusters and CSI driver plugin for integrating aks with private keyvault . We have AzureDevops CI CD pipelines to deploy the applications to each environment with the helm manifests.

Since we have to manage different clusters in same nonprod subscriptions(dev,stg and prepod) , we were looking for a way to run them in a single common nonprod cluster and run all the 3 nonprod envts (dev,stg, and preprod) as isolated clusters without changing any of its behaviors explained above  like, azureCNI enabled, separate service mesh configuration and different subscriptions kv integration etc..

### Which solution do you suggest?

By going through the vcluster document, we couldn't confirm , whether the vcluster is supported in aks private clusters and can we install the vcluster opensource version in aks cluster with all the above requirements are fulfilled ?

**Comment by facchettos** [comment]
hi! 
Vcluster supports air-gapped environments, so it is possible to use it with azure private clusters. Since the pods are running on AKS, you will have azure CNI working with it. The different service mesh configuration on each cluster is most likely possible, however it may depend on the service mesh that you are using, and you might also try to install the services meshes directly inside the vclusters if the previous solution isn't possible. Regarding the kv integration, it will probably depend on how azure handles it, and if you can have different rules for different namespaces.

**Comment by vivuu1989** [comment]
> hi! Vcluster supports air-gapped environments, so it is possible to use it with azure private clusters. Since the pods are running on AKS, you will have azure CNI working with it. The different service mesh configuration on each cluster is most likely possible, however it may depend on the service mesh that you are using, and you might also try to install the services meshes directly inside the vclusters if the previous solution isn't possible. Regarding the kv integration, it will probably depend on how azure handles it, and if you can have different rules for different namespaces.

is there any document how this vcluster opensource extension can be installed in AKS ?

**Comment by facchettos** [comment]
what extension are you referring to? To install vCluster in an air-gapped environment or similar, you should follow this documentation https://www.vcluster.com/docs/getting-started/deployment
