### ISSUE TITLE
[bug] panic in 0.20.0-beta.11 when Endpoint cache sync times out

### ISSUE THREAD

**Issue by mtougeron** [loft-sh/vcluster#1909]
### What happened?

When the host cluster's apiserver is slow to respond or has a timeout, vcluster's `syncer` container will have a panic and crash.

```
panic: failed to wait for kubernetes_default_endpoint caches to sync: timed out waiting for cache to be synced for Kind *v1.Endpoints

goroutine 418 [running]:
github.com/loft-sh/vcluster/pkg/setup.StartManagers.func1()
	github.com/loft-sh/vcluster/pkg/setup/controllers.go:218 +0x45
created by github.com/loft-sh/vcluster/pkg/setup.StartManagers in goroutine 385
	github.com/loft-sh/vcluster/pkg/setup/controllers.go:215 +0x98
```

### What did you expect to happen?

I would have expected the panic to be caught/handled and vcluster to try again

### How can we reproduce it (as minimally and precisely as possible)?

I've only seen this happen on heavily loaded host cluster apiservers when the apiserver on the host cluster sometimes times out.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.28.9-eks-036c24b
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.20.0-beta.11
```

</details>

### VCluster Config

I was able to replicate the issue with a default installation with no custom values file.

```sh
helm upgrade --install touge-test vcluster --version 0.20.0-beta.11 --repo https://charts.loft.sh --namespace touge-test --repository-config=''
```

<details>

```
# My vcluster.yaml / values.yaml here
```

</details>

**Comment by facchettos** [comment]
Hi! thanks for opening the issue. This is the wanted behaviour, since there is no guarantee that it will be working when we subsequently retry. Panicking _may not_ be the cleanest solution here, but even if we change it, the behaviour won't change and we will be exiting with an error. 

Since the statefulset will restart the failed pod, waiting for the api to be available will be done with that, with the benefit of using back offs and not putting unnecessary load on an already shaky host k8s API

**Comment by mtougeron** [comment]
> Is there any reason why you consider this a bug?

It was the panic aspect mostly that I considered the bug. My assumption was that it would retry with a backoff without crashing the pod so it doesn't end up in a CLBO state.

> Is it preventing your workflow?

No. It does mean that we have to run in HA mode in more scenarios but in the grand scheme of things we probably should be anyway.

**Comment by facchettos** [comment]
>It was the panic aspect mostly that I considered the bug. My assumption was that it would retry with a backoff without crashing the pod so it doesn't end up in a CLBO state.

I'll look into something a little cleaner than a panic. But I am not seeing the issue with CLBO, since that indicates clearly what the problem is without having to dig through the logs and looking for the retries. That also follows the `fail fast` design principle 

>No. It does mean that we have to run in HA mode in more scenarios but in the grand scheme of things we probably should be anyway. 

So yeah, running it in HA mode would maybe reduce the risk, but in any case, if we can't start the controllers/managers, even with in process retries, it would not really be available technically (since it would not be able to sync anything to the host cluster)

**Comment by mtougeron** [comment]
I'm fine if you want to close this as intended behavior.
