### ISSUE TITLE
Failed to cordon node in virtual cluster

### ISSUE THREAD

**Issue by fishingfly** [loft-sh/vcluster#2121]
### What happened?

When I use this command to cordon node in k8s cluster which created by vCluster.
``` bash
kubectl cordon node <node-name>
```
the status of node is as follows:
![image](https://github.com/user-attachments/assets/ce208f77-64ed-4efc-bc10-59de9537e99a)

### What did you expect to happen?

Node can be cordoned in cluster

### How can we reproduce it (as minimally and precisely as possible)?

In virtual cluster, use this command to cordon node:
``` bash
kubectl cordon node <node-name>
```
At the same time, you need to watch node status by this command:
```bash
kubectl get node -w
```

### Anything else we need to know?

I see the code https://github.com/loft-sh/vcluster/blob/v0.19.6/pkg/controllers/resources/nodes/translate.go#L25,  `translateUpdateBackwards` func will update virtual node spec by host node spec.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### vcluster version

0.19.6

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
```

</details>

**Comment by yeahdongcn** [comment]
We've encountered the same issue (by accident). Just wondering if this is by design or if it needs to be fixed.

**Comment by FabianKramm** [comment]
Hey @yeahdongcn @fishingfly ! Thanks for reporting this issue! That is actually expected behaviour for the default configuration as nodes shouldn't be changed within the vCluster as that would break isolation. There are however 2 ways that should achieve what you want to do:
1. Enable the virtual scheduler which allows you to add labels, taints and other changes to the virtual nodes and prevents pods from getting scheduled there. You can enable that via `controlPlane.advanced.virtualScheduler.enabled=true` (https://vcluster.com/docs/vcluster/configure/vcluster-yaml/control-plane/other/advanced/virtual-scheduler), which has the advantage that cordoning a node within the virtual cluster won't mark it unschedulable in the host cluster, so pods on the host are unaffected by this.
2. Allow syncing back node changes via `sync.fromHost.nodes.syncBackChanges=true` (https://vcluster.com/docs/vcluster/next/configure/vcluster-yaml/sync/from-host/nodes#sync-real-nodes-and-sync-back-labels-and-taints), which will sync taints and labels to the host cluster. This means that if you cordon a node within the virtual cluster it will get unschedulable for everyone including pods on the host cluster.

**Comment by yeahdongcn** [comment]
Thank you for the detailed explanation. Option 1 seems like the better choice for us since it won’t impact the host cluster.
