### ISSUE TITLE
provide guidance how to backup vcluster and its workloads

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#246]
We need to provide guidance for users how they can backup vcluster and its workloads correctly. We might even need to implement some "rewriting" mechanism for important host paths to support common backup solutions like velero. This requires further investigation.

**Comment by olljanat** [comment]
Related to #193 There I mentioned that Kasten is one interesting option because it supports restoring to environment which uses different CSI plugin than original source. Or that is at least what my old colleague who works on Veeam nowadays was saying. One quite common use case on their customers environment is taking backups from on-prem and do DR testing on AKS/GCE.

However I haven't had time to test it my self yet.

**Comment by FabianKramm** [comment]
@olljanat that makes sense, yeah we'll probably need to evaluate certain solutions and check what easiest to use with vcluster.

**Comment by matskiv** [comment]
@FabianKramm would you say this is addressed now that the #694 and #785 are merged?

**Comment by matskiv** [comment]
Done in PRs mentioned above.
