### ISSUE TITLE
DaemonSet Pods stays on node even if no other workload is present

### ISSUE THREAD

**Issue by wcarlsen** [loft-sh/vcluster#252]
This might be intentional, so please close the issue if so and thanks for a wonderful project btw.

**What**
When spinning up a multi node cluster with e.g. minikube and deploying a nginx:latest deployment with a single replica, I only see the node where the workload is scheduled. I then scale the deployment to 10 replicas and I see more nodes, because of the 10 workload Pods being spread out by the scheduler. I then scale down to a single replica again and I see a single node after some waiting around. It is all to be expected.

But when I do the same procedure with a DaemonSet deployed, my node count never goes back down due to the DaemonSet workloads still running on those nodes even no other relevant workloads are running on those nodes.

**Expected behavior**
I would have expected the DaemonSet Pods to be terminated (after some time) on the nodes where no relevant workload is running in order to minimize unnecessary vcluster workload pressure on the "mother ship" cluster.

**Test spec**
* Vcluster version 0.4.5 (latest available version at the time)
* Minikube version v1.24.0
* Kubectl version v1.22.4

```bash
# 0) Spin up minikube test cluster
minikube start --cpus 2 --memory 2048 --nodes=3 --cni=flannel

# 1) Create vcluster
vcluster create vcluster1 -n vcluster1 --create-namespace --disable-ingress-sync

# 2) Connect to vcluster
vcluster connect vcluster1 -n vcluster1

# 3) Create deployment
kubectl --kubeconfig ./kubeconfig.yaml create deployment workload --image=nginx:latest --replicas=1

#  4) Scale deployment
kubectl --kubeconfig ./kubeconfig.yaml scale deployment workload --replicas=10

# 5) Get nodes
 kubectl --kubeconfig ./kubeconfig.yaml get nodes

# 6) Scale down
kubectl --kubeconfig ./kubeconfig.yaml scale deployment workload --replicas=1

# 7) Get nodes (OBS: you have to wait for the count to go down)
 kubectl --kubeconfig ./kubeconfig.yaml get nodes

# 8) Apply DaemonSet
cat <<EOF | kubectl --kubeconfig ./kubeconfig.yaml create -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nginx
  name: daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
EOF

# Repeat from step 4 up and including step 7
```

**Comment by FabianKramm** [comment]
@wcarlsen thanks for creating this issue! Currently this is expected as vcluster determines if a node is not needed anymore if there is no workload scheduled on that node. vcluster does not distinguish currently between daemonset workloads and other workloads which is why the node in your case is never deleted. Currently we recommend using the [node-selector flag](https://www.vcluster.com/docs/architecture/nodes#node-syncing-modes) as this will also delete nodes that do not match the node selector anymore.

**Comment by wcarlsen** [comment]
Thanks @FabianKramm then think of this as a feature request and you suggestion is certainly doable.

**Comment by kfox1111** [comment]
Could the syncer just filter out the pods with:
```
metadata:
  ownerReferences:
  - apiVersion: apps/v1
    kind: DaemonSet
```

I don't think it would need any special permissions to determine that?

**Comment by FabianKramm** [comment]
@kfox1111 sorry for letting this hang so long, yes I guess thats very possible to do.

**Comment by wcarlsen** [comment]
Thanks @kfox1111 I managed to delete nodes with only DaemonSets running from the vcluster, so that `kubectl get nodes` from the vcluster shows the correct number of nodes. So that is awesome! Unfortunately the "unwanted" DaemonSet pods is still running and visible, so I will need to attack the pod syncer as well.

**Comment by kfox1111** [comment]
Hmm... that brings up an interesting edge case....

What happens if a user deletes a node on the overcluster that has pods on it? It should probably delete them all.
What about automatically too? Say the undercluster admin deletes a node because its malfunctioning? That should cause the overcluster to delete the node too, and also delete all the pods off of it.

**Comment by wcarlsen** [comment]
@kfox1111 good thinking. I will try to test the edge cases because I think it somewhat relates to this issue and report back if I spot anything fishy.

**Comment by wcarlsen** [comment]
@kfox1111 so I have now tested two scenarios and got a little more clever on things.

Scenario 1 - Admin deletes node on physical cluster:
Normal Pods stemming from Deployments get rescheduled as expected, but DaemonSets ends up in a pending or containercreation state for about 1 minute before disappearing. So in conclusion this seems to work kind of well.

Scenario 2 - Vcluster user deletes a "virtual node":
The node might be quickly deleted, but is very fast added again with and the AGE resets to 0s so the node is not really deleted and the vcluster user  has no power to be picky about nodes. It kind of makes a lot of sense, but in the case of malfunctioning nodes and a physical cluster admin not being fast enough this might be a problem. Even if I try to cordon a node as vcluster user and then drain it, the pods are just rescheduled on that cordoned node.

**Comment by wcarlsen** [comment]
@FabianKramm it seems like the fix above was included in release v0.6, but unfortunately I can confirm that the vcluster still cannot scale down in terms of lonely daemonsets on nodes, so I'm leaving this one open. It seems that some changes was applied later around the logic of filtering or it may be very poor testing on my part. Either way I will take another crack at this, since I find it gives and extra punch to that cost savings argument.

If you have any inputs/insights please let me know.

**Comment by wcarlsen** [comment]
Okay I think I found the root cause. It turns out that at least for DaemonSets deployed inside a vcluster, when the resulting pods are synced to the underlying cluster the ownerReferences is all messed up. For a 3 node cluster two of the pods (with origin in a DaemonSet) have `kind: Service` and the last has `kind: StatefulSet` on the physical cluster. This makes filtering on ownerRef kind of useless. Too me it seems strange if this is intentional?

**Comment by kfox1111** [comment]
This feels familiar.... let me try and find the reference...

**Comment by kfox1111** [comment]
This: https://github.com/loft-sh/vcluster/issues/273

**Comment by pratikjagrut** [comment]
In this pr #321, we did some changes to the owner reference, so this may be causing the issue.

**Comment by pratikjagrut** [comment]
Syncer is also adding some annotations while syncing pods to the physical cluster. So annotaion `vcluster.loft.sh/owner-set-kind: DaemonSet` could be used to filter out the daemonset pods.

**Comment by wcarlsen** [comment]
I will try to modify the daemonset filter method specifically for the physical cluster. Thanks for the valuable input @pratikjagrut 💪

**Comment by pratikjagrut** [comment]
@wcarlsen Happy to help. :)

**Comment by ddl-risong-na** [comment]
@wcarlsen we recently started to use vcluster. We have multiple vclusters with identical deployments. We deployed cluster autoscaler on the host cluster, but it is not able to scale down nodes due to daemonsets. There are some nodes that only have daemonsets pods running. Our suspicion is that those host cluster level pods are not recognized as controlled by daemonsets, so the auto scaler is not able to unschedule them.

We are interested in how you made it work for you. Do you have autoscaler deployed on the host cluster or on each vclusters? How did you make the autoscaler unschedule daemonset pods that were not recognized as daemonset pods on the host cluster?

vcluster folks, I have asked the same question on your slack, sorry for spamming...
