### ISSUE TITLE
Keep Labels on ingress sync

### ISSUE THREAD

**Issue by zachaller** [loft-sh/vcluster#27]
The labels seem to be blown away on the synced ingress object, these should probably be kept so that things like cert-manager can still be configured.

**Comment by FabianKramm** [comment]
@zachaller thanks for creating this issue! In the next version we will keep the labels for all objects (currently things like downwardAPI volumes won't work for `metadata.labels["my-label"]`), however we will rewrite them, as they could collide within a namespace with labels of other objects, so we have to ensure the labels are unique per vcluster per namespace within the vcluster in the host cluster

**Comment by matskiv** [comment]
I think this was not implemented due to security concerns. I'll close this issue since there are multiple workaround options as described below. 

We have a flag that allows setting explicitly allowed labels, and those will be synced on all resources without changing the label key:
```
syncer:
  extraArgs:
    - --sync-labels=syncThisKey,andThisKey
    - --sync-labels=andAnotherKey
```

Also, we introduced a [plugin system for vcluster](https://www.vcluster.com/docs/plugins/overview) through which you could modify the behavior of vcluster. And one of the plugins that we created handles the cert-manager use case - [cert-manager-plugin](https://github.com/loft-sh/vcluster-plugins/tree/master/cert-manager-plugin).
