### ISSUE TITLE
Enabled tenant cluster can support different k8s distro

### ISSUE THREAD

**Issue by gyliu513** [loft-sh/vcluster#423]
### Is your feature request related to a problem?

Many people are using different k8s distros, like RH OpenShift and some others, so how to enable I can have my tenant cluster as RH OpenShift Cluster?

### Which solution do you suggest?

Can we enable I can install a RH OpenShift tenant cluster?

### Which alternative solutions exist?

N/A

### Additional context

*No response*

**Comment by FabianKramm** [comment]
@gyliu513 thanks for creating this issue! Currently we only support k0s, k3s, vanilla k8s & eks as tenant distros, but in general other distributions shouldn't be too difficult to add (as described [here](https://www.vcluster.com/docs/operator/other-distributions#other-distributions)). At the moment we don't support RH OpenShift out of the box as a tenant distro, since we don't have a chart for it, but I don't see a reason why this shouldn't work in general. 

Would you be willing to give this a shot? Since OpenShift is adding quite a bunch of extra resources, I wonder if we might need to add some extra syncers for it, but we could take a look at this later on I guess and create an OpenShift chart first.

**Comment by gyliu513** [comment]
Yes, OCP is adding a bunch of extra resources here, like ocp apiserver etc, then in the tenant cluster, it will have not only kube api server, kube controller manager, storage, but also other ocp extra resources, let me put this in my backlog and check later. Thanks @FabianKramm

**Comment by FabianKramm** [comment]
@gyliu513 I see, thanks for your response. I guess it would already be nice for us to know whats missing in vcluster exactly (if there is anything missing besides the chart) to enable OpenShift as a potential tenant. Would be really great if you find some time to investigate this or even create a PR for this. We also have this on our backlog, but I'm not sure yet when we'll be able to implement this, so any help is greatly appreciated!
