### ISSUE TITLE
vCluster TCP Socket Fails

### ISSUE THREAD

**Issue by donmstewart** [loft-sh/vcluster#788]
### What happened?

A socket exposed through ingress-nginx on the vCluster is terminating connections or has large latencies on connection which cause clients to timeout.

### What did you expect to happen?

External apps can connect to a TCP socket (not HTTP) on the vCluster

### How can we reproduce it (as minimally and precisely as possible)?

Use `--tcp-services-configmap=nginx/tcp-services` on nginx Deployment to point to a config map with exposed TCP sockets e.g.

apiVersion: v1
kind: ConfigMap
metadata:
name: tcp-services
namespace: nginx
data:
'1234': my-namespace/svc:4321

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Amazon EKS 1.22
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# vcluster version 0.11.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
Linux gpudb-0 5.4.209-116.367.amzn2.x86_64 #1 SMP Wed Aug 31 00:09:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

**Comment by matskiv** [comment]
The vcluster is designed to utilize host cluster network layer for the workloads (with the exception of DNS), so it doesn't interact with any application network requests except for the requests to the vcluster API server.
Unless nginx is exposed via `kubectl port-forward`, the vcluster is very unlikely to cause the performance issues you are seeing.
Can you please provide more information based on which you attribute this problem to vcluster? That would be very helpful for moving forward. Thank you. :slightly_smiling_face:

**Comment by donmstewart** [comment]
If we run our workload, which has a couple of TCP layer 3/4 sockets as well as HTTP layer 7 ingress, on the EKS cluster hosting the vCluster it works. If we move the workload into the vCluster on the same EKS it does not. HTTP works, TCP ports are intermittent.

So are you suggesting as vcluster uses the `host cluster` networking that the TCP ports be opened on the ingress-nginx on the host or that it should already just work in the vCluster?

**Comment by matskiv** [comment]
It should already work in the vcluster.
I mentioned that it uses host cluster networking to support my thesis that it is unlikely that vcluster could cause the drop in network performance. Workloads deployed to vcluster (this includes nginx in this case) end up running in the host cluster (pods and services are copied but with name and label changes).
I think what I failed to take into account in my previous comment(in my defence it was Friday afternoon :joy: ), is that the problem happens when a connection is being established. I guess at that point nginx is doing a DNS resolution of the target (`my-namespace/svc` from your example config). 
Would you be able to test if the same problem is present for targets that you define in the `--tcp-services-configmap` by their `.spec.clusterIP` instead of the DNS name?

**Comment by donmstewart** [comment]
I am leaning towards ruling out it being vcluster because if I deploy a socat pod/svc and expose it externally then have the socat pod forward to our pod/svc internally it always works. 

The weird thing is on EKS & AKS natively this does not occur only in vcluster.

I will try out the `.spec.clusterIP` though to rule that out. Thanks for the pointer.

**Comment by alexandradragodan** [comment]
Hey, @donmstewart 👋 

Thanks again for reporting this issue. 
We're eager to hear how that `.spec.clusterIP` try went out for you!

Please let us know if there's anything we can support you with! 
Thank you for your promptitude.

**Comment by matskiv** [comment]
Closing based on the lack of reply. I am happy to reopen if new information is provided.
