### ISSUE TITLE
Set port to expose `vcluster create --expose`

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#88]
In my cluster, using `--expose` does not work because the Service does not come up:

```
Error syncing load balancer: failed to ensure load balancer: Service cannot use 80 and 443 port
```

But if I manually create the load balancer service with port 8443, then it works. So it would come very in handy if I could set the port to be used in the `vcluster create` command.

**Comment by FabianKramm** [comment]
@felipecrs thanks for creating this issue! Yes we can add an option for this

**Comment by FabianKramm** [comment]
@felipecrs unfortunately this is not possible on the `vcluster` service itself, because it is also used as Kubernetes service which requires port 443. The only workaround I see is to create a separate LoadBalancer service with a different port that uses the same label selector, like you would do if you create another load balancer manually.

**Comment by felipecrs** [comment]
I see...

**Comment by felipecrs** [comment]
This issue isn't meaningful for me any longer, therefore I'm closing it. If you believe the opposite, feel free to reopen it.
