### ISSUE TITLE
[Question] Cloning virtual Clusters ?

### ISSUE THREAD

**Issue by emirot** [loft-sh/vcluster#994]
### Is your feature request related to a problem?

I would like to use virtual cluster in order to tests Kuberentes Operators and others k8s custom components.
Virtual Clusters sound to me like a good idea, I would like to know if once I have a Vcluster I can easily copy/clone that vcluster to multiple entities to make the testing fast, easily reproducible etc ?

### Which solution do you suggest?

I was reading [https://www.vcluster.com/docs/operator/backup](https://www.vcluster.com/docs/operator/backup) and one solution could be to have the initial environment create a backup run the test and then restore to previous state ?

### Which alternative solutions exist?

The one I just mentioned

### Additional context

*No response*

**Comment by matskiv** [comment]
We don't have a cloning/snapshotting feature yet.

Besides using velero, one alternative comes to mind, but we didn't test it AFAIK. If you don't use any PVCs/PVs inside your virtual cluster, and you want to restore just the state of the Kubernetes resources, you could try making a [Kubernetes snapshot](https://kubernetes.io/docs/concepts/storage/volume-snapshots/) of the vcluster volume. Then to restore you can use `volumeClaimTemplates` helm value to set the `.spec.volumeClaimTemplates` field of the vcluster StatefulSet, in which you can reference the Snapshot as the source. If you do try this, I'd love to hear how it went :) 

btw, how long does it take you to get the vcluster into the initial state? I am asking because vcluster itself starts pretty fast, and the init manifests/charts feature ([docs](https://www.vcluster.com/docs/operator/init-manifests)) could help you with bootstrapping the instance, so would it still be worth it to make a more complex backup-restore process?

**Comment by matskiv** [comment]
@emirot The limitations, and whether it is a good idea, depends on what exactly is the use case. If your platform needs to interact with some low-level things (e.g. you have custom CNI/CSI), then vcluster doesn't work with that. Another limitation is NodePorts - the port numbers are shared within the whole host cluster, so if your app requires an exact NodePort number, that won't work. Otherwise, with the right configuration, it should work fine. Afterall, vcluster is a certified Kubernetes distro :). [Here](https://github.com/loft-sh/vcluster/tree/main/conformance/v1.26)
 you can find the config that we use to run conformance tests, and the results.

If you don't insist on using snapshots, and instead you are able to just automate the installation of all the dependencies before the test run, then you can start using vcluster quicker. But of course, using or not using snapshots is a tradeoff between test stability and catching things early.

**Comment by matskiv** [comment]
There was no reply for 2 weeks now, so I'll close the issue. We can re-open if any follow-up comments are added.

**Comment by emirot** [comment]
Thanks @matskiv yes we can close, I have custom CNI but maybe in can use vcluster for some other use cases.
